### ISSUE TITLE
实现平行四边形 

### ISSUE THREAD

**Issue by vivipure** [vivipure/js-challenges-answer#34]
# 答案
使用 skewX
```css
.parallelogram {
  width: 200px;
  height: 200px;
  background: red;
  transform: skewX(18deg);
}
```
