### ISSUE TITLE
宽高自适应正方形

### ISSUE THREAD

**Issue by vivipure** [vivipure/js-challenges-answer#40]
# 答案

## 1. aspect-ratio
```css
    .square {
      aspect-ratio: 1 / 1;
      background: red;
    }
```
## 2. padding-top 实现hack
```css
 .square {
      padding-top: 100%;
      height: 0;
      background: red;
}
```
