### ISSUE TITLE
CSS 多行文字截断

### ISSUE THREAD

**Issue by vivipure** [vivipure/js-challenges-answer#44]
# 答案
使用 `-webkit-box`,`-webkit-line-clamp: 3`,`-webkit-box-orient: vertical`
```css
    .ellipsis {
      width: 100px;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
```
