### ISSUE TITLE
黑白主题切换

### ISSUE THREAD

**Issue by vivipure** [vivipure/js-challenges-answer#46]
# 答案
通过 filter 即可
```css

html.dark-mode {
  filter: grayscale(100%);
}


html.light-mode {
  filter: none;
}
```
